export const syllabusDataNoImage = [
  {
    avatar1Prop: '',
    avatar2Prop: '',
    avatar3Prop: '',
    courseNameProp: 'Linux',
    activeProp: 'Active',
    isBtnDeleteProp: false,
    versionProp: 'LIN v2.0',
    durationProp: '4 days (12 hours)',
    modifiedDateProp: '23/07/2022',
    modifiedAuthorProp: 'Johny Deep',
  },
  {
    avatar1Prop: '',
    avatar2Prop: '',
    avatar3Prop: '',
    courseNameProp: 'AWS Basic',
    activeProp: 'Active',
    isBtnDeleteProp: false,
    versionProp: 'AWB v1.0',
    durationProp: '7 days (21 hours)',
    modifiedDateProp: '23/07/2022',
    modifiedAuthorProp: 'Warrior Tran',
  },
  {
    avatar1Prop: '',
    avatar2Prop: '',
    avatar3Prop: '',
    courseNameProp: 'Docker',
    activeProp: 'Active',
    isBtnDeleteProp: false,
    versionProp: 'DOC v1.5',
    durationProp: '3 days (12 hours)',
    modifiedDateProp: '23/07/2022',
    modifiedAuthorProp: 'Warrior Tran',
  },
  {
    avatar1Prop: '',
    avatar2Prop: '',
    avatar3Prop: '',
    courseNameProp: 'Kubernetes',
    activeProp: 'Active',
    isBtnDeleteProp: false,
    versionProp: 'KUB v1.5',
    durationProp: '6 days (18 hours)',
    modifiedDateProp: '23/07/2022',
    modifiedAuthorProp: 'Ba Chu Heo',
  },
  {
    avatar1Prop: '',
    avatar2Prop: '',
    avatar3Prop: '',
    courseNameProp: 'Devops_CICD',
    activeProp: 'Active',
    isBtnDeleteProp: false,
    versionProp: 'DEC v2',
    durationProp: '8 days (24 hours)',
    modifiedDateProp: '23/07/2022',
    modifiedAuthorProp: 'Ba Chu Heo',
  },
  {
    avatar1Prop: '',
    avatar2Prop: '',
    avatar3Prop: '',
    courseNameProp: 'Mock Project',
    activeProp: 'Inactive',
    isBtnDeleteProp: false,
    versionProp: 'MOC v2.5',
    durationProp: '3 days (12 hours)',
    modifiedDateProp: '23/07/2022',
    modifiedAuthorProp: 'Ba Chu Heo',
  },
  {
    avatar1Prop: '',
    avatar2Prop: '',
    avatar3Prop: '',
    courseNameProp: 'Field Trip',
    activeProp: 'Active',
    isBtnDeleteProp: false,
    versionProp: 'MOC v2.5',
    durationProp: '1 days (5 hours)',
    modifiedDateProp: '23/07/2022',
    modifiedAuthorProp: 'Ba Chu Heo',
  },
]
