import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Action, Delivery } from '../../../../assets/svg';
import styles from './Header.module.css';
export default function Header({ title = 'Fresher Develop Operation', classTitle = 'HCM22_FR_DevOps_01', day = 31, time = 97, classOnly = false, editHeader = false, date, name, button, }) {
    if (classOnly) {
        return (_jsx("div", { className: styles.headerOnly, children: _jsx("h3", { className: styles.headerClassTop, children: "Class" }) }));
    }
    else if (editHeader) {
        return (_jsxs("div", { className: styles.headerEdit, children: [_jsxs("div", { className: styles.headerInfoEdit, children: [_jsxs("div", { className: styles.headerDetailEdit, children: [_jsx("h3", { className: styles.headerClassTopEdit, children: classTitle }), _jsxs("div", { className: styles.headerNameEdit, children: [_jsx("h2", { children: title }), button] })] }), _jsx("div", { className: styles.headerMoreEdit, children: _jsx(Action.MoreHorizontalIcon, { color: editHeader ? 'black' : 'white', width: 30, height: 30 }) })] }), _jsxs("div", { className: styles.headerActionEdit, children: [_jsxs("div", { className: styles.headerDayEdit, children: [_jsx("span", { className: styles.mainText, children: day }), _jsxs("span", { className: styles.subText, children: ["days (", time, " hours)"] })] }), _jsx("div", { className: styles.headerDayModified, children: _jsxs("span", { children: ["Modified on ", date, " by ", name] }) })] })] }));
    }
    return (_jsxs("div", { className: styles.header, children: [_jsxs("div", { className: styles.headerInfo, children: [_jsxs("div", { className: styles.headerDetail, children: [_jsx("h3", { className: styles.headerClassTop, children: "Class" }), _jsxs("div", { className: styles.headerName, children: [_jsx("h2", { children: title }), button] }), _jsx("h3", { className: styles.headerClassBottom, children: classTitle })] }), _jsx("div", { className: styles.headerMore, children: _jsx(Action.MoreHorizontalIcon, { color: "white", width: 30, height: 30 }) })] }), _jsxs("div", { className: styles.headerAction, children: [_jsxs("div", { className: styles.headerDay, children: [_jsx("span", { className: styles.mainText, children: day }), _jsxs("span", { className: styles.subText, children: ["days (", time, " hours)"] })] }), _jsxs("div", { className: styles.headerBtn, children: [_jsx("button", { children: _jsx(Delivery.AssignmentIcon, { color: "white" }) }), _jsx("button", { children: _jsx(Delivery.ConceptIcon, { color: "white" }) }), _jsx("button", { children: _jsx(Delivery.ExamIcon, { color: "white" }) }), _jsx("button", { children: _jsx(Delivery.SeminarIcon, { color: "white" }) }), _jsx("button", { children: _jsx(Delivery.GuideIcon, { color: "white" }) })] })] })] }));
}
