import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import { Accordion, AccordionTab } from 'primereact/accordion';
import TagContained from '../../../components/Tag/TagContained';
import styles from './ProgramDetailContent.module.css';
import TagOutlined from '../../../components/Tag/TagOutlined';
export default function ProgramDetailContent({ course, calculateDuration, formatDate, admin, courseSchedule, }) {
    console.log(courseSchedule);
    const Header = (_jsxs("div", { children: [_jsxs("div", { className: "flex mb-2 items-center justify-between ", children: [_jsxs("div", { className: "flex  items-center gap-10  ", children: [_jsxs("h4", { children: [" ", course.courseName, " "] }), _jsx(TagContained, { value: course.status })] }), _jsx("div", { children: _jsx(TagContained, { icon: "pi pi-arrow-right" }) })] }), _jsxs("div", { className: "flex gap-4  text-sm  ", children: [_jsxs("p", { children: [" ", course.courseAlias, " "] }), _jsx("p", { children: "|" }), _jsxs("p", { children: [calculateDuration(course.startTime, course.endTime), " days (12 hours)"] }), _jsx("p", { children: "|" }), _jsxs("p", { children: ["Modified on ", formatDate(course.creationDate), " by ", admin, ' '] })] })] }));
    return (_jsxs("div", { className: `${styles.content} px-[30px]`, children: [_jsx("h3", { className: " font-bold text-[24px] ", children: "Content" }), courseSchedule &&
                courseSchedule.map((course, index) => {
                    return (_jsx(Accordion, { className: "shadow-xl w-[100%] px-[20px] py-[14px] rounded-sm ", children: _jsx(AccordionTab, { header: Header, children: _jsx(Accordion, { className: "mb-0.5 mt-2 ", children: course.schedule.map(day => (_jsx(AccordionTab, { header: _jsxs("p", { className: "text-white  ", children: [" ", day.day, " "] }), className: "bg-primary shadow-lg mb-2 overflow-hidden  ", children: _jsx(Accordion, { className: "mb-0.5 ", children: day.units.map((unit, index) => {
                                            return (_jsx(AccordionTab, { header: _jsx("div", { className: "", children: _jsxs("div", { className: "flex  gap-10 ", children: [_jsxs("p", { className: " text-[18px] font-bold ", children: ["Unit ", index + 1] }), _jsx("div", { children: _jsxs("h5", { children: [_jsx("p", { className: "font-bold mb-2", children: unit.unitName }), _jsx("p", { children: "6 hrs" })] }) }), _jsx("div", { className: "ml-auto", children: _jsx("i", { className: "pi pi-chevron-circle-down" }) })] }) }), className: "border-b-[1px]", children: _jsxs("div", { className: "flex gap-16  ", children: [_jsx("p", { className: " invisible ", children: "Test" }), _jsx("div", { className: "flex-1", children: unit.miniUnits.map(miniUnit => (_jsx("div", { className: " bg-gray px-[20px] py-2 rounded-[10px] mb-1", children: _jsxs("div", { className: "flex items-center", children: [_jsx("div", { className: "flex-1 ", children: _jsx("h6", { className: "font-bold", children: miniUnit.miniUnitName }) }), _jsxs("div", { className: "flex gap-10 items-center ", children: [_jsx(TagContained, { value: "K65D" }), _jsx("p", { children: "10 mins" }), miniUnit.isOnline ? (_jsx(TagOutlined, { value: "online" })) : (_jsx(TagContained, { value: "offline" })), _jsx("i", { className: "pi pi-user" }), _jsx("i", { className: "pi pi-folder" })] })] }) }))) })] }) }, unit.unitName));
                                        }) }) }, day.day))) }) }) }, index));
                }), !courseSchedule && _jsx("p", { children: "Not Data Found" })] }));
}
